version: "3.7"

services:
  redis: 
    image: redislabs/redisearch
    ports:
      - '6379:6379'
    networks:
      - backend
  
  app:
    build: flask-app
    ports:
      - '5000:5000'
    networks:
      - backend
    environment:
      - REDIS_OM_URL=redis://redis:6379

    depends_on:
      - redis

networks:
  backend: